version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: insightdb
      POSTGRES_USER: insight
      POSTGRES_PASSWORD: insight
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: